name: RegionLock
version: '1.0-SNAPSHOT'
main: me.olios.plugins.regionLock.RegionLock
api-version: '1.21'
depend:
  - ProtocolLib
commands:
  RegionLock:
    aliases:
      - region
      - rl
    description: Main command for the RegionLock plugin.
    usage: /<command> <subcommand>
    permission: RegionLock.admin.commands

permissions:
    RegionLock.*:
      default: op
